apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:password@db:5432/guests_db
            - name: FLASK_ENV
              value: development
          image: 430771536635.dkr.ecr.eu-west-1.amazonaws.com/k8s
          name: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
